- .idea/compiler.xml
- .idea/misc.xml
- GatewayService/src/main/resources/application.yml
After discussion with @JeffreyYou , it is decided that service uri routing should start with a namespace of the service's same.
> Update Gateway URI Matching Rule

- UserService/pom.xml
- UserService/src/main/java/com/beaconfire/userservice/controller/UserAuthController.java
- UserService/src/main/java/com/beaconfire/userservice/domain/User.java
No tests done yet, for sync and initialization purpose.
> Added Auth Controller and User Domain POJO

- reddit-frontend/src/components/HomePage.scss
- reddit-frontend/src/components/HomePage.tsx
- reddit-frontend/src/components/NewPost.scss
- reddit-frontend/src/components/NewPost.tsx
- reddit-frontend/src/components/Posts.scss
- reddit-frontend/src/components/Posts.tsx
> User Home Page Layout initial commit

- .idea/dataSources.xml
- UserService/pom.xml
- UserService/src/main/java/com/beaconfire/userservice/controller/UserAuthController.java
- UserService/src/main/java/com/beaconfire/userservice/dto/ChangePasswordRequest.java
- UserService/src/main/java/com/beaconfire/userservice/dto/EmailVerificationConfirmationRequest.java
- UserService/src/main/java/com/beaconfire/userservice/dto/UserAuthenticationRequest.java
- UserService/src/main/java/com/beaconfire/userservice/dto/UserRegistrationRequest.java
- UserService/src/main/resources/application.yml
1. Added User Service Auth Controller DTOs. 
2. Established Database Connection.
3. Removed API for email verification initialization, that API should be include in Auth Service.
> Added User Service Auth Controller DTOs and Established Database Connection

- UserService/src/main/java/com/beaconfire/userservice/controller/UserProfileController.java
> Added UserProfile Controller with Basic Method Signatures

- .idea/misc.xml
- .idea/uiDesigner.xml
- UserService/pom.xml
- UserService/src/main/java/com/beaconfire/userservice/config/EncoderConfig.java
- UserService/src/main/java/com/beaconfire/userservice/config/SecurityConfig.java
- UserService/src/main/java/com/beaconfire/userservice/controller/UserAuthController.java
- UserService/src/main/java/com/beaconfire/userservice/controller/UserMgmtController.java
- UserService/src/main/java/com/beaconfire/userservice/dao/UserRepository.java
- UserService/src/main/java/com/beaconfire/userservice/dto/UserAuthRequest/ChangePasswordRequest.java
- UserService/src/main/java/com/beaconfire/userservice/dto/UserAuthRequest/EmailVerificationConfirmationRequest.java
- UserService/src/main/java/com/beaconfire/userservice/dto/UserAuthRequest/UserAuthenticationRequest.java
- UserService/src/main/java/com/beaconfire/userservice/dto/UserAuthRequest/UserRegistrationRequest.java
- UserService/src/main/java/com/beaconfire/userservice/dto/UserAuthResponse/AuthenticationResponse.java
- UserService/src/main/java/com/beaconfire/userservice/dto/UserAuthResponse/ChangePasswordResponse.java
- UserService/src/main/java/com/beaconfire/userservice/dto/UserAuthResponse/EmailVerificationResponse.java
- UserService/src/main/java/com/beaconfire/userservice/dto/UserAuthResponse/UserRegistrationResponse.java
- UserService/src/main/java/com/beaconfire/userservice/exception/UserAlreadyExistsException.java
- UserService/src/main/java/com/beaconfire/userservice/exception/UserNotFoundException.java
- UserService/src/main/java/com/beaconfire/userservice/service/UserAuthService.java
- UserService/src/main/resources/application.yml
Took 1 hour 11 minutes
Took 9 minutes
- Further complete API response DTOs
- Implement User Register API
- Initial DAO layer
- Initial Service layer
- Added configuration for password encoder and Spring Security
- Initial Exception pacakage
Tested through postman. Gateway->Service->Database
> Added responses DTOs to APIs and implement user register API

- package-lock.json
- reddit-frontend/package-lock.json
- reddit-frontend/package.json
- reddit-frontend/src/App.tsx
- reddit-frontend/src/components/LoginPage.scss
- reddit-frontend/src/components/LoginPage.tsx
- reddit-frontend/src/components/Navbar.scss
- reddit-frontend/src/components/Navbar.tsx
- reddit-frontend/src/components/RegisterPage.scss
- reddit-frontend/src/components/RegisterPage.tsx
- reddit-frontend/src/router.tsx
Add the Home page, rotuer, Navbar Login and Register Page
> Feature: Navbar Login and Register Page

- UserService/src/main/java/com/beaconfire/userservice/controller/UserProfileController.java
- UserService/src/main/java/com/beaconfire/userservice/domain/User.java
- UserService/src/main/java/com/beaconfire/userservice/dto/UserProfileRequest/UpdateUserProfileRequest.java
- UserService/src/main/java/com/beaconfire/userservice/dto/UserProfileResponse/UpdateUserProfileResponse.java
- UserService/src/main/java/com/beaconfire/userservice/dto/UserProfileResponse/UserProfileFieldResponse.java
- UserService/src/main/java/com/beaconfire/userservice/dto/UserProfileResponse/UserProfileListResponse.java
- UserService/src/main/java/com/beaconfire/userservice/dto/UserProfileResponse/UserProfileResponse.java
- UserService/src/main/java/com/beaconfire/userservice/service/UserProfileService.java
> added user profile updates

- MessageService/pom.xml
- MessageService/src/main/java/com/beaconfire/messageservice/config/SecurityConfig.java
- MessageService/src/main/java/com/beaconfire/messageservice/controller/ContactAdminController.java
- MessageService/src/main/java/com/beaconfire/messageservice/controller/MessageManagementController.java
- MessageService/src/main/java/com/beaconfire/messageservice/dao/MessageRepository.java
- MessageService/src/main/java/com/beaconfire/messageservice/domain/Message.java
- MessageService/src/main/java/com/beaconfire/messageservice/dto/ContactAdminRequest.java
- MessageService/src/main/java/com/beaconfire/messageservice/dto/ContactAdminResponse.java
- MessageService/src/main/java/com/beaconfire/messageservice/dto/MessageListResponse.java
- MessageService/src/main/java/com/beaconfire/messageservice/dto/MessageResponse.java
- MessageService/src/main/java/com/beaconfire/messageservice/dto/UpdateMessageStatusRequest.java
- MessageService/src/main/java/com/beaconfire/messageservice/dto/UpdateMessageStatusResponse.java
- MessageService/src/main/java/com/beaconfire/messageservice/security/AuthUserDetail.java
- MessageService/src/main/java/com/beaconfire/messageservice/security/JwtFilter.java
- MessageService/src/main/java/com/beaconfire/messageservice/security/JwtProvider.java
- MessageService/src/main/java/com/beaconfire/messageservice/security/User.java
- MessageService/src/main/java/com/beaconfire/messageservice/service/ContactAdminService.java
- MessageService/src/main/java/com/beaconfire/messageservice/service/MessageManagementService.java
- MessageService/src/main/java/com/beaconfire/messageservice/service/UserAuthService.java
- MessageService/src/main/resources/application.yml
> Added user's contact admin functionality

- AuthService/src/main/java/com/beaconfire/authservice/service/AuthLoginService.java
- UserService/src/main/java/com/beaconfire/userservice/config/SecurityConfig.java
- UserService/src/main/java/com/beaconfire/userservice/security/JwtFilter.java
> Backend dev user service siweiz a

- GatewayService/src/main/resources/application.yml
- UserService/src/main/java/com/beaconfire/userservice/config/SecurityConfig.java
- UserService/src/main/java/com/beaconfire/userservice/controller/UserAuthController.java
- UserService/src/main/java/com/beaconfire/userservice/controller/UserMgmtController.java
- UserService/src/main/java/com/beaconfire/userservice/controller/UserProfileController.java
fix cors problems for gateway & user service
> BugFix: fix cors problems for gateway & user service

- .idea/compiler.xml
- .idea/encodings.xml
- .idea/misc.xml
- FileService/pom.xml
- FileService/src/main/java/com/beaconfire/fileservice/config/AWSConfig.java
- FileService/src/main/java/com/beaconfire/fileservice/config/SecurityConfig.java
- FileService/src/main/java/com/beaconfire/fileservice/controller/FileController.java
- FileService/src/main/java/com/beaconfire/fileservice/dto/response/StatusResponse.java
- FileService/src/main/java/com/beaconfire/fileservice/security/AuthUserDetail.java
- FileService/src/main/java/com/beaconfire/fileservice/security/JwtFilter.java
- FileService/src/main/java/com/beaconfire/fileservice/security/JwtProvider.java
- FileService/src/main/java/com/beaconfire/fileservice/security/JwtService.java
- FileService/src/main/java/com/beaconfire/fileservice/service/FileService.java
- FileService/src/main/resources/application.yml
- UserService/src/main/java/com/beaconfire/userservice/config/SecurityConfig.java
> file service Zhihang 

- reddit-frontend/src/pages/user-profile/index.tsx
- reddit-frontend/src/store/interface.ts
- reddit-frontend/src/store/user-store.ts
- reddit-frontend/src/store/util.ts
fetch user profile
fetch user top3 posts
fetch user draft posts
> Feature: User store update

- PostAndReplyService/src/main/java/com/beaconfire/postandreplyservice/config/FeignClientConfig.java
- PostAndReplyService/src/main/java/com/beaconfire/postandreplyservice/controller/PostController.java
- PostAndReplyService/src/main/java/com/beaconfire/postandreplyservice/controller/ReplyController.java
- PostAndReplyService/src/main/java/com/beaconfire/postandreplyservice/security/JwtFilter.java
- PostAndReplyService/src/main/java/com/beaconfire/postandreplyservice/util/JwtTokenHolder.java
- PostAndReplyService/src/main/java/com/beaconfire/postandreplyservice/util/JwtTokenRequestInterceptor.java
Took 1 hour 35 minutes
- Added JwtTokenRequestInterceptor to allow Feign client to make request with JWT
> Updated Feign Client to Make Request w JWT in Header

- MessageService/src/main/java/com/beaconfire/messageservice/dto/msgmgmt/MessageResponse.java
- MessageService/src/main/java/com/beaconfire/messageservice/service/MessageManagementService.java
> return message id to front end

- PostAndReplyService/src/main/java/com/beaconfire/postandreplyservice/controller/PostController.java
> Backend dev postreplydix tianhao

- reddit-frontend/src/components/contact-admin-form/ContactAdminForm.tsx
- reddit-frontend/src/pages/contact/ContactAdminPage.tsx
- reddit-frontend/src/pages/contact/style.module.scss
- reddit-frontend/src/router.tsx
- reddit-frontend/src/store/contact-admin-store.ts
- reddit-frontend/src/store/interface.ts
To fix:
1. ContactAdminPage component overlapping with Nav Bar
2. Access current user's jwt token, currently using dummy token
> added simple contact-admin page

- reddit-frontend/src/pages/message-management/MessageMgmtPage.tsx
- reddit-frontend/src/pages/message-management/style.module.scss
- reddit-frontend/src/router.tsx
- reddit-frontend/src/store/interface.ts
- reddit-frontend/src/store/message-management-store.ts
Toggle the status of a message:
> added basic message management page

- reddit-frontend/src/components/forms/user-edit-email/index.tsx
- reddit-frontend/src/components/forms/user-edit-profile/index.tsx
- reddit-frontend/src/components/user-profile-card/index.tsx
- reddit-frontend/src/components/user-profile-card/style.module.scss
- reddit-frontend/src/pages/user-profile/index.tsx
- reddit-frontend/src/pages/user-profile/style.module.scss
- reddit-frontend/src/router.tsx
- reddit-frontend/src/store/user-store.ts
> Feature: user profile finalize

- CompositeService/pom.xml
- GatewayService/src/main/resources/application.yml
- pom.xml
fix composite service name issue and add it on gateway.
> fix composite service name issue and add it on gateway

- UserService/pom.xml
- UserService/src/main/java/com/beaconfire/userservice/controller/UserAuthController.java
- UserService/src/main/java/com/beaconfire/userservice/exception/GlobalExceptionHandler.java
- UserService/src/main/java/com/beaconfire/userservice/exception/InvalidUserPasswordException.java
- UserService/src/main/java/com/beaconfire/userservice/security/JwtProvider.java
- UserService/src/main/java/com/beaconfire/userservice/service/UserAuthService.java
- UserService/src/main/java/com/beaconfire/userservice/service/UserMgmtService.java
- UserService/src/test/java/com/beaconfire/userservice/controller/UserAuthControllerTest.java
- UserService/src/test/java/com/beaconfire/userservice/controller/UserMgmtControllerTest.java
- UserService/src/test/java/com/beaconfire/userservice/controller/UserProfileControllerTest.java
- UserService/src/test/java/com/beaconfire/userservice/exception/GlobalExceptionHandlerTest.java
- UserService/src/test/java/com/beaconfire/userservice/security/JwtFilterTest.java
- UserService/src/test/java/com/beaconfire/userservice/security/JwtProviderTest.java
- UserService/src/test/java/com/beaconfire/userservice/service/UserAuthServiceTest.java
- UserService/src/test/java/com/beaconfire/userservice/service/UserMgmtServiceTest.java
- UserService/src/test/java/com/beaconfire/userservice/service/UserProfileServiceTest.java
- Complete Unit Tests for User Service
- Minor Fix to Remove Unesseray Codes
> Complete Unit Tests for User Service

- CompositeService/src/main/java/com/beaconfire/compositeservice/dto/PostResponse.java
- CompositeService/src/main/java/com/beaconfire/compositeservice/service/CompositeService.java
> Composite service fixed

- .idea/encodings.xml
- .idea/misc.xml
- FileService/src/main/java/com/beaconfire/fileservice/config/SecurityConfig.java
> Backend file zhihang

- reddit-frontend/src/components/post/Posts.tsx
- reddit-frontend/src/pages/home/HomePage.tsx
- reddit-frontend/src/store/post-store.ts
> add Home Page Posts

- reddit-frontend/src/pages/home-admin/HomeAdminPage.tsx
- reddit-frontend/src/store/post-store.ts
> Frontend admin homepage
